name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  code-review:
    uses: asleep-ai/actions/.github/workflows/code-review.yml@main
    with:
      language: English
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
